version: "3.8"

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    ports:
      - "4000:8080"
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped
  deepgraph-rag-service:
    container_name: deepgraph-rag-service
    # use this to dev local app
    # build: .
    image: faywong8888/deepseek-private-chatbot:latest
    # Map Streamlit's default port 8501 in the container to 8501 on the host.
    ports:
      - "8501:8501"
    
    # Environment variables for .env usage or direct injection (optional).
    # If you have a .env file, Docker Compose can load them with env_file: .env
    # Or define them inline:
    environment:
      - OLLAMA_API_URL=http://localhost:11434
      - MODEL=deepseek-r1:8b
      - EMBEDDINGS_MODEL=rjmalagon/gte-qwen2-1.5b-instruct-embed-f16:latest
      - CROSS_ENCODER_MODEL=BAAI/bge-reranker-large

    # (Optional) If you want to mount your local code into the container for live development:
    # volumes:
    #   - .:/usr/src/app

    # If you want to override the Dockerfile CMD:
    # command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - searxng
